version: "3.8"

services:
  ## http
  http-pub:
    build:
      context: ./server-pub
      dockerfile: http.Dockerfile
    environment:
      PORT: 3000
      SUB_HOST: "172.27.0.3:3001"
    ports:
      - "3000:3000"
    networks:
      - test-nw
  http-sub:
    build:
      context: ./server-sub
      dockerfile: http.Dockerfile
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - test-nw

  ## grpc

  ## eda

networks:
  test-nw:
