version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: Users
      MYSQL_ROOT_PASSWORD: 12341234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
